version: '3.6'

services:
  worker:
    build: .
    image: logwork-worker:1.0.0
    container_name: worker
    restart: always
    environment:
      - JIRA_PROTOCOL=https
      - JIRA_HOST=jira.younetco.com
      - JIRA_POST=80
      - JIRA_API_VERSION=2
