version: '3.6'

services:
  worker:
    build: .
    image: logwork-worker:1.0.1
    container_name: worker
    restart: always
    environment:
      - JIRA_PROTOCOL=https
      - JIRA_HOST=jira.younetco.com
      - JIRA_POST=80
      - JIRA_API_VERSION=2
      - JIRA_USER=user
      - JIRA_PASS=pass
      - JOB_SCHEDULE_RULE=40 17 * * 1-5
      - JOB_ISSUE_ID_OR_KEY=abc
      - JOB_TIMESPENT=1d
      - JOB_COMMENT=comment
